### PR TITLE
Add Chakra-blog

### PR DESCRIPTION
**Pull request by xuwillie**
Add Chakra-blog

### CODE REVIEW

**Comment by nikolovlazar** [comment]
@xuwillie is this a template that everyone can use, or your personal website?

**Comment by xuwillie** [comment]
Everyone can use. I will improve it

**Comment by nikolovlazar** [comment]
> Everyone can use. I will improve it

In that case change the text to say that it's your personal website.

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
> Everyone can use. I will improve it

In that case change the text to say that it's your personal website.

**Review by nikolovlazar — CHANGES_REQUESTED** [review]
> Everyone can use. I will improve it

In that case change the text to say that it's your personal website.

**Comment by nikolovlazar** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
